language: c
compiler:
    - gcc

before_install:
    - sudo pip install codecov

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq libcunit1 libcunit1-dev lcov

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
    - make coverage

after_success:
    - codecov
